<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\CustomAdminLogo\ViewModel\AdminLogo;
use Magento\Backend\Block\Page\Header;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Header $block */
$part = $block->getShowPart();

/** @var AdminLogo $adminLogoViewModel */
$adminLogoViewModel = $block->getData('admin_logo_view_model');
?>
<?php if ($part === 'logo'): ?>
    <?php $edition = $block->hasEdition()
        ? 'data-edition="' . $escaper->escapeHtml($block->getEdition()) . '"'
        : ''; ?>
    <?php $adminLoginLogoSrc = $adminLogoViewModel->getAdminLogoModel()->getCustomAdminLoginLogoSrc(); ?>
    <?php $adminMenuLogoSrc = $adminLogoViewModel->getAdminLogoModel()->getCustomAdminMenuLogoSrc(); ?>

    <a href="<?= $escaper->escapeUrl($block->getHomeLink()); ?>"
       <?= /* @noEscape */ $edition; ?>
       class="logo">
        <img class="logo-img"
             <?php if ($adminLogoViewModel->isAdminLoginPage()): ?>
                 src="<?= $escaper->escapeUrl(
                     $adminLoginLogoSrc ?: $block->getViewFileUrl('images/mage-os-logo.svg')
                 ); ?>"
             <?php else: ?>
                 src="<?= $escaper->escapeUrl(
                     $adminMenuLogoSrc ?: $block->getViewFileUrl('images/mage-os-icon.svg')
                 ); ?>"
             <?php endif; ?>
             alt="<?= $escaper->escapeHtmlAttr(__('Mage-OS Admin Panel')); ?>"
             title="<?= $escaper->escapeHtmlAttr(__('Mage-OS Admin Panel')); ?>"/>
    </a>
<?php elseif ($part === 'user'): ?>
    <div class="admin-user admin__action-dropdown-wrap">
        <a href="<?= $escaper->escapeUrl($block->getUrl('adminhtml/system_account/index')); ?>"
           class="admin__action-dropdown"
           title="<?= $escaper->escapeHtmlAttr(__('My Account')); ?>"
           data-mage-init='{"dropdown":{}}'
           data-toggle="dropdown">
            <span class="admin__action-dropdown-text">
                <span class="admin-user-account-text">
                    <?= $escaper->escapeHtml($block->getUser()->getUserName()); ?>
                </span>
            </span>
        </a>
        <ul class="admin__action-dropdown-menu">
            <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')): ?>
                <li>
                    <a href="<?= $escaper->escapeUrl($block->getUrl('adminhtml/system_account/index')); ?>"
                       <?= /* @noEscape */ $block->getUiId('user', 'account', 'settings'); ?>
                       title="<?= $escaper->escapeHtmlAttr(__('Account Setting')); ?>">
                        <?= $escaper->escapeHtml(__('Account Setting')); ?>
                        (<span class="admin-user-name">
                            <?= $escaper->escapeHtml($block->getUser()->getUserName()); ?>
                        </span>)
                    </a>
                </li>
            <?php endif; ?>

            <li>
                <a href="<?= $escaper->escapeUrl($block->getBaseUrl()); ?>"
                   title="<?= $escaper->escapeHtmlAttr(__('Customer View')); ?>"
                   target="_blank"
                   class="store-front">
                    <?= $escaper->escapeHtml(__('Customer View')); ?>
                </a>
            </li>
            <li>
                <a href="<?= $escaper->escapeUrl($block->getLogoutLink()); ?>"
                   class="account-signout"
                   title="<?= $escaper->escapeHtmlAttr(__('Sign Out')); ?>">
                    <?= $escaper->escapeHtml(__('Sign Out')); ?>
                </a>
            </li>
        </ul>
    </div>
<?php elseif ($part === 'other'): ?>
    <?= $block->getChildHtml(); ?>
<?php endif; ?>
