<?php
/**
 * Copyright © Mage-OS, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$hints = [
    'base_url' => sprintf(
        '<div><p>%s</p><p>%s</p></div>',
        'Enter the base URL that brings shoppers to your store (Ex. http://example.com/).',
        'Leave empty for automatic detection (not recommended for production environment).'
    ),
    'encrypt_key' => sprintf(
        '<p>%s</p>',
        'Key to encrypt sensitive data such as passwords and personally identifiable customer information in the Mage-OS database. The encryption key is stored in [your Mage-OS install dir]/app/etc/env.php'
    ),
    'admin' => sprintf(
        '<p>%s</p>',
        'A unique URL helps keep your store and customers safer. Use only letters, numbers, and underscore characters.'
    )
];
?>

<div class="page-web-configuration">

<div class="nav-bar-outer-actions">
    <div class="outer-actions-inner-wrap">
        <div class="btn-wrap btn-wrap-triangle-right btn-wrap-next">
            <button type="button" class="btn btn-prime" ng-click="validateUrl()" dis>Next</button>
        </div>
        <div class="btn-wrap btn-wrap-triangle-left btn-wrap-prev">
            <button type="button" class="btn" ng-click="previousState()">Back</button>
        </div>
    </div>
</div>

<h2 class="page-sub-title">{{$state.current.header}}</h2>
<p>
    <span class="field-note"> Set up the primary URLs and advanced web settings for your Mage-OS store</span>
</p>

<div
    class="message message-error"
    ng-show="validateUrl.failed !== undefined"
>
    <span class="message-text">{{validateUrl.failed}}</span>
</div>

<form
    name="webconfig"
    role="form"
    novalidate
    >

<fieldset class="form-fieldset">

    <div
        class="row form-row"
        ng-class="{'has-error': webconfig.base_url.$invalid && webconfig.submitted}"
        >
        <div class="col-m-4">
            <label class="form-label" for="baseUrl">
                Your Store Address
            </label>
        </div>
        <div class="col-m-8">
            <input
                id="baseUrl"
                class="form-el-input"
                type="url"
                name="base_url"
                ng-model="config.address.base_url"
                ng-class="{'invalid': webconfig.base_url.$invalid && webconfig.submitted}"
                ng-init="config.address.auto_base_url = '<?= $this->autoBaseUrl ?>'; fillBaseURL();"
                ng-blur="addSlash()"
                ng-change="populateHttps()"
                ng-pattern="/^(https?:\/\/).*$/"
                tooltip-placement="right"
                tooltip-html-unsafe="<?= $hints['base_url'] ?>"
                tooltip-trigger="focus"
                tooltip-append-to-body="true"
                >

            <div class="error-container">
                <span ng-show="!webconfig.base_url.valid
                                || webconfig.base_url.$error.required
                                || webconfig.base_url.$error.url"
                >
                    Please enter a valid base URL path. (ex: http://www.example.com/)
                </span>
            </div>
            <div>
                <span class="field-note">
                    This is the base URL where your Mage-OS storefront will be accessible. This is the main link that your customers will use to visit your online store
                </span>
            </div>
        </div>


    </div>

    <div
        class="row form-row"
        ng-class="{'has-error': webconfig.admin.$invalid && webconfig.submitted}"
        >
        <div class="col-m-4">
            <label class="form-label required" for="admin">
                Admin URL
            </label>
        </div>
        <div class="col-m-8">
            <div class="form-el-insider-wrap">
                <div class="form-el-insider">
                    {{config.address.actual_base_url}}
                </div>
                <div class="form-el-insider-input">
                    <input
                        id="admin"
                        class="form-el-input"
                        type="text"
                        name="admin"
                        ng-pattern="/^[a-zA-Z0-9_]+$/"
                        ng-model="config.address.admin"
                        ng-class="{'invalid' : webconfig.admin.$invalid && webconfig.submitted }"
                        ng-init="config.address.admin = '<?= $this->autoAdminPath ?>';"
                        required
                        tooltip-placement="right"
                        tooltip-html-unsafe="<?= $hints['admin'] ?>"
                        tooltip-trigger="focus"
                        tooltip-append-to-body="true"
                        >
                    <div class="error-container">
                        <span ng-show="webconfig.admin.$error">
                            Please enter a valid admin URL path. Use only letters, numbers, and underscore characters.
                        </span>
                    </div>
                </div>
            </div>
            <span class="field-note">
                        The specific URL where you can access the Mage-OS admin dashboard. This is where you'll manage all the backend operations for your store.
                    </span>
        </div>
    </div>

</fieldset>

<fieldset class="form-fieldset">

    <legend
        class="form-legend-expand"
        ng-click="updateOnExpand(config.advanced)"
        ng-class="{'expanded' : config.advanced.expanded}"
        >
        Advanced Options
    </legend>

    <div ng-show="config.advanced.expanded">

        <div class="row form-row">
            <div class="col-m-4">
                <label class="form-label">
                    HTTPS Options
                </label>
            </div>
            <div class="col-m-8">
                <div class="form-row">
                    <input
                        id="httpsFront"
                        class="form-el-checkbox"
                        type="checkbox"
                        ng-model="config.https.front"
                        ng-checked="config.https.front"
                        >
                    <label class="form-label" for="httpsFront">
                        Use HTTPS for Mage-OS Storefront <br />
                        <span class="legend-note">
                             This option enables a secure connection for your storefront using the HTTPS protocol. It's highly recommended for security and for gaining the trust of your customers.
                        </span>
                    </label>
                </div>
                <div class="form-row">
                    <input
                        id="httpsAdmin"
                        class="form-el-checkbox"
                        type="checkbox"
                        ng-model="config.https.admin"
                        ng-checked="config.https.admin"
                        >
                    <label class="form-label" for="httpsAdmin">
                        Use HTTPS for Mage-OS Admin <br />
                        <span class="legend-note">
                            Activates a secure HTTPS connection for the Mage-OS admin dashboard. This enhances security for backend operations.
                        </span>
                    </label>
                </div>
            </div>
        </div>

        <div class="row form-row" ng-show="showHttpsField()">
            <div class="col-m-4">
                <label
                    ng-show="config.https.front || config.https.admin"
                    class="form-label"
                    for="https"
                    >
                    Your HTTPS Store address:
                </label>
            </div>
            <div class="col-m-8">
                <input
                    id="https"
                    class="form-el-input"
                    type="url"
                    name="https"
                    ng-model="config.https.text"
                    ng-class="{'invalid': webconfig.https.$invalid && webconfig.submitted}"
                    ng-if="config.https.front || config.https.admin"
                    ng-focus=""
                    ng-pattern="/^(https?:\/\/).*$/"
                    required
                    >
                <div class="error-container">
                    <span ng-show="!webconfig.https.$error.valid
                                    || webconfig.https.$error.required
                                    || webconfig.https.$error.url"
                    >
                        Please enter a valid HTTPS base URL path. (ex: https://www.example.com/)
                    </span>
                </div>
                <div>
                <span class="field-note">
                    The secure version of your store URL if HTTPS is enabled.
                </span>
                </div>
            </div>

        </div>

        <div class="row form-row">
            <div class="col-m-4">
                <label class="form-label">
                    Apache Rewrites
                </label>
            </div>
            <div class="col-m-8">
                <input
                    id="apacheRewrites"
                    class="form-el-checkbox"
                    type="checkbox"
                    ng-model="config.rewrites.allowed"
                    >
                <label class="form-label" for="apacheRewrites">
                    Use Apache Web Server Rewrites <br />
                    <span class="legend-note">This option allows you to simplify URLs for your store pages by removing the "index.php" part from them. It provides cleaner URLs which are better for SEO and user experience.</span>
                    <span class="legend-note">(select only if you are using Apache web server)</span>
                </label>
            </div>
        </div>

        <div class="row form-row">
            <div class="col-m-4">
                <label class="form-label required">
                    Encryption Key
                </label>
            </div>
            <div class="col-m-8">

                <div class="form-row">
                    <input
                        id="encryptionKey"
                        class="form-el-radio"
                        type="radio"
                        ng-model="config.encrypt.type"
                        value="magento"
                        >
                    <label class="form-label" for="encryptionKey">
                        I want to use a Mage-OS generated key <br />
                        <span class="legend-note">
                            Let Mage-OS generate a secure encryption key for you. This key is used to encrypt sensitive data in the database.
                        </span>
                    </label>
                </div>

                <div class="form-row">
                    <input
                        id="encryptionType"
                        class="form-el-radio"
                        type="radio"
                        ng-model="config.encrypt.type"
                        value="user"
                        >
                    <label class="form-label" for="encryptionType">
                        I want to use my own encryption key <br />
                        <span class="legend-note">
                            If you have a specific encryption key you want to use, or if you're migrating from another store and want to use the same key, choose this option.
                        </span>
                    </label>
                </div>

                <div
                    class="form-row"
                    ng-class="{'has-error': webconfig.key.$invalid && webconfig.submitted}"
                    ng-if="showEncryptKey()"
                    >
                    <input
                        class="form-el-input"
                        type="text"
                        name="key"
                        ng-model="config.encrypt.key"
                        ng-class="{'invalid': webconfig.key.$invalid && webconfig.submitted}"
                        tooltip-placement="right"
                        tooltip-html-unsafe="<?= $hints['encrypt_key'] ?>"
                        tooltip-trigger="focus"
                        tooltip-append-to-body="true"
                        ng-minlength="4"
                        required
                        >
                    <div class="error-container">
                        <span ng-show="webconfig.key.$error.required">
                            You must enter an encryption key.
                        </span>
                        <span ng-show="webconfig.key.$error.minlength">
                            Your encryption key must be longer and stronger.
                        </span>
                    </div>
                </div>

            </div>
        </div>

        <div class="row form-row">
            <div class="col-m-4">
                <label class="form-label required">
                    Session Save
                </label>
            </div>
            <div class="col-m-8">
                <select
                    name="session"
                    class="form-el-select"
                    ng-model="config.sessionSave.type"
                    ng-class="{'invalid': webconfig.session.$invalid && webconfig.submitted}"
                    tooltip-placement="right"
                    tooltip-html-unsafe="The location of session. You can change this later in Mage-OS Admin."
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true"
                    >
                    <?php foreach ($this->sessionSave as $value):?>
                        <?= "<option value=\"" . $value . "\">" . ucfirst($value) . "</option>" ?>
                    <?php endforeach; ?>
                </select>
                <div>
                <span class="field-note">
                    This option determines where Mage-OS will save session data. Session data includes information about a user's interactions with the site, such as items added to a shopping cart, login states, and more. Choosing the right option can impact the performance and scalability of your store.
                </span>
                </div>
            </div>

        </div>

    </div>
</fieldset>
</form>

</div>
