git add app/code/Magento/Catalog/Test/Unit/Block/Product/ListProductTest.php
git add app/code/Magento/Catalog/Test/Unit/Controller/Adminhtml/Category/RefreshPathTest.php
git add app/code/Magento/Catalog/Test/Unit/Controller/Adminhtml/Product/Action/Attribute/SaveTest.php
git add app/code/Magento/Catalog/Test/Unit/Controller/Adminhtml/Product/AddAttributeToTemplateTest.php
git add app/code/Magento/Catalog/Test/Unit/Controller/Adminhtml/Product/Attribute/EditTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Attribute/Backend/TierPrice/SaveHandlerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Attribute/Backend/TierPrice/UpdateHandlerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Category/Link/ReadHandlerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Category/TreeTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/CategoryLinkRepositoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/CategoryManagementTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/CategoryRepositoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/CategoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Config/Source/CategoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ConfigTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/CustomOptions/CustomOptionTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Entity/AttributeTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Indexer/Category/Flat/System/Config/ModeTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Indexer/Product/Eav/Plugin/StoreViewTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Layer/Filter/DataProvider/PriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Layer/Filter/PriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/LayerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Plugin/QuoteItemProductOptionTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/ActionTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Backend/CategoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Backend/GroupPrice/AbstractTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Backend/PriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Backend/StockTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Backend/TierpriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Source/StatusTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/CopyConstructor/CrossSellTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/CopyConstructor/RelatedTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/CopyConstructor/UpSellTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Gallery/ProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Initialization/Helper/ProductLinksTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Link/ConverterTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/LinkTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Option/Type/FileTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Price/BasePriceStorageTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Price/PricePersistenceTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Price/SpecialPriceStorageTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Price/Validation/InvalidSkuProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Type/AbstractTypeTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/UrlTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Website/ReadHandlerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/Product/Website/SaveHandlerTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ProductIdLocatorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ProductOptionProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ProductRepository/MediaGalleryProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/AttributeTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/MediaImageDeleteProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/StatusBaseSelectProcessorTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Price/SpecialPriceBulkResolverTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Price/TierPriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Render/FinalPriceBoxTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/RenderTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/WebsitesTest.php
git add app/code/Magento/CatalogInventory/Test/Unit/Model/Indexer/Stock/Action/FullTest.php
git add app/code/Magento/CatalogRule/Test/Unit/Model/RuleTest.php
git add app/code/Magento/CatalogWidget/Test/Unit/Model/Rule/Condition/ProductTest.php
git add app/code/Magento/CatalogWidget/Test/Unit/Model/RuleTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Attribute/Edit/Tab/AdvancedTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Edit/Action/Attribute/Tab/InventoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Edit/Tab/InventoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Helper/Form/GalleryTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Helper/Form/WeightTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Options/AjaxTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Category/Plugin/PriceBoxTagsTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/AbstractProductTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/Compare/ListCompareTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/ContextTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/ListProductTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/ProductList/RelatedTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Product/ProductList/ToolbarTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Rss/CategoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Rss/Product/NewProductsTest.php
git add app/code/Magento/Catalog/Test/Unit/Block/Ui/ProductViewCounterTest.php
git add app/code/Magento/Catalog/Test/Unit/Cron/RefreshSpecialPricesTest.php
git add app/code/Magento/Catalog/Test/Unit/Plugin/Model/Attribute/Backend/AttributeValidationTest.php
git add app/code/Magento/Catalog/Test/Unit/Plugin/Model/AttributeSetRepository/RemoveProductsTest.php
git add app/code/Magento/Catalog/Test/Unit/Plugin/Model/Indexer/Category/Product/ExecuteTest.php
git add app/code/Magento/Catalog/Test/Unit/Plugin/Model/ResourceModel/Attribute/SaveTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Price/SpecialPriceBulkResolverTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Price/TierPriceTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/Render/FinalPriceBoxTest.php
git add app/code/Magento/Catalog/Test/Unit/Pricing/RenderTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CustomOptionsTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/EavTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/WebsitesTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/ProductDataProviderTest.php
git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/ProductCustomOptionsDataProviderTest.php

