<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Page\Copyright;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Copyright $block */
?>
<a class="link-copyright"
   href="https://mage-os.org/"
   target="_blank"
   title="<?= $escaper->escapeHtmlAttr(__('Mage-OS')); ?>">
</a>
<?= $escaper->escapeHtml(__('Mage-OS %1.', date('Y'))); ?>
