<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $expressions = []; foreach ( $this->main as $item ): ?>
    <?php $expressions[] = '!$state.is(\'' . $item['id'] . '\')';
    ?>
<?php endforeach; ?>
<?php
    $expressions[] = '!$state.is(\'\')';
    $expressions[] = !$this->isInstaller ? 'true' : 'false';
?>

<div class="menu-wrapper"
    ng-show="<?= implode( '&&', $expressions) ?>"
    >
<nav class="admin__menu" ng-controller="mainController">
    <span class="logo logo-static" data-edition="Community Edition">
        <img class="logo-img" src="<?= $this->basePath() ?>/pub/images/mageos/logomark.svg" alt="MageOS Admin Panel">
    </span>

</nav>
</div>
