	git add app/code/Magento/Catalog/Test/Unit/Model/Category/Link/SaveHandlerTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/CustomOptions/CustomOptionProcessorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Indexer/Product/Eav/AbstractActionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Indexer/Product/Eav/Plugin/AttributeSet/IndexableAttributeFilterTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Indexer/Product/Fl	t/Action/EraserTest.php/ct	
	git add app/code/Magento/Catalog/Test/Unit/Model/Layer/Filter/AttributeTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Layer/Filter/CategoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Layer/Filter/FactoryTest.p
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/Frontend/ImageTest.phpnfig
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/TypesListTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/LinkTypeProviderTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Option/Type/FactoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/OptionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Pricing/Renderer/SalableResolverTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Type/AbstractTypeTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/Type/PriceTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Product/TypeTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ProductRender/FormattedPriceInfoBuilderTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ProductRepositoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ProductTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/AbstractTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/CatalogCategoryAndProductResolverOnSingleStoreModeT
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/AggregateCountTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/Collection/FactoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/CollectionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/FlatTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/TreeTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/CategoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/ConfigTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Eav/AttributeTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Indexer/ActiveTableSwitcherTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/MediaImageDeleteProcessorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/ActionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/CategoryLinkTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Collection/JoinMinimalPositionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/CollectionTest.ph
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/CompositeBaseSelectProcessorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/FlatTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/GalleryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/ImageTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Eav/BatchSizeCalculatorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Eav/DecimalRowSizeEstimatorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Eav/SourceTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/LinkedProductSelectBuilderByIndexPriceTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Price/BatchSizeCalculatorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Price/CompositeProductRowSizeEstimatorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/Price/IndexTableRowSizeEstimatorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Indexer/TemporaryTableStrategyTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Link/Product/CollectionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/LinkTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Option/CollectionTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/StatusBaseSelectProcessorTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/Website/LinkTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/ProductWebsiteAssignmentHandlerTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Rss/Product/NewProductsTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Rss/Product/NotifyStockTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Rss/Product/SpecialTest.php
	git add app/code/Magento/Catalog/Test/Unit/Model/Template/Filter/FactoryTest.php

	git add app/code/Magento/Catalog/Test/Unit/Observer/SetSpecialPriceStartDateTest.php

	git add app/code/Magento/Catalog/Test/Unit/Setup/Patch/Data/UpdateMultiselectAttributesBackendTypesTest.php

	git add app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php

	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/CatalogEavValidationRulesTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/AbstractModifierTestCase.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/AdvancedPricingTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/AttributeSetTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/AttributesTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CategoriesTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CurrencySymbolProviderTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CustomOptionsTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/EavTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/FactoryTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/GeneralTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/RelatedTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/SystemTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/TierPriceTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/Modifier/WebsitesTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Form/ProductDataProviderTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Listing/Collector/AdditionalInfoTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Listing/Collector/ImageTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Listing/Collector/PriceTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/Listing/Collector/UrlTest.php
	git add app/code/Magento/Catalog/Test/Unit/Ui/DataProvider/Product/ProductCustomOptionsDataProviderTest.php

	